site_name: Ceramic Developers
site_url: https://developers.ceramic.network
site_description: Specs, docs, guides, and APIs for the Ceramic Network.
repo_url: https://github.com/ceramicnetwork/js-ceramic
repo_name: ceramicnetwork/js-ceramic
edit_uri: https://github.com/ceramicnetwork/docs/edit/main/docs/

# Copyright
copyright: 'Ceramic is open sourced under MIT and Apache 2'


theme:
  name: material
  custom_dir: overrides
  # 404 page
  static_templates:
    - 404.html
  palette:
    scheme: default 
  logo: images/ceramic-no-shadow.png
  icon:
    repo: fontawesome/brands/github-alt
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - header.autohide

nav:
  - Learn:
    #- Welcome: learn/welcome.md
    - Overview: learn/overview.md
    #- Clients: learn/clients.md
    #- Networks: learn/networks.md
    #- Ecosystem: learn/ecosystem.md
  - Build:
    - Quick Start: build/quick-start.md
    - Installation: build/installation.md
    - Authentication: build/authentication.md
    - Writes: build/writes.md
    - Queries: build/queries.md
    - Pinning: build/pinning.md
    - Share your work: build/share.md
    - Troubleshooting: build/troubleshooting.md
  #- Run:
    #- Ceramic node: run/ceramic-node.md
    #- Anchor service: run/anchor-service.md
  - Tools:
    - Standards:
      - StreamTypes:
        #- Overview:
        - Tile Document:
        - CAIP-10 Link:
      #- Schemas:
        #- Overview:
        #- BasicProfile:
        #- 3ID Keychain:
        #- Also Known As:
        #- AppendCollection:
      #- DIDs:
        #- Overview: tools/standards/dids/overview.md
        #- 3ID DID: tools/standards/dids/3id.md
        #- Key DID: tools/standards/dids/key.md
    - Dev Tools:
      - Authentication:
        - 3ID Connect: tools/dev-tools/authentication/3id-connect.md
      - Identity:
        - IDX: tools/dev-tools/identity/idx.md
        - IdentityLink: tools/dev-tools/identity/identitylink.md
        - Self.id: tools/dev-tools/identity/self-id.md
      #- Hosting:
        #- Community nodes:
        #- Community anchor services:
        #- Hosting providers: tools/hosting/hosting-providers.md
  - Reference:
    - JavaScript:
      - Clients: reference/javascript/clients.md
      - DID Resolvers: reference/javascript/did-resolvers.md
      - DID Providers: reference/javascript/did-providers.md
      - Support new Blockchain: reference/javascript/blockchain.md
      - Anchor Service: reference/javascript/anchor-service.md
    - HTTP API: reference/http-api.md
  - Chat: 'https://chat.ceramic.network'
  - Blog: 'https://blog.ceramic.network'

markdown_extensions:
  - meta
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3

extra:
  generator: false
  # Social icons in footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ceramicnetwork/ceramic
      name: Ceramicnetwork on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ceramicnetwork
      name: Ceramicnetwork on Twitter

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

extra_css:
  - stylesheets/extra.css

plugins:
    - redirects:
        redirect_maps:
            'index.md': 'learn/overview.md'
    - search
